version: '2'
services:
  db:
    image: 'mysql:5.7'
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_MAJOR=5.7
      - max_sp_recursion_depth=12
    volumes:
      - './docker/db:/var/lib/mysql'
      - '/mysql.cnf:/etc/my.cnf'
    ports:
      - '100:3306'
  rest-api:
    image: 'java:openjdk-8-jre-alpine'
    ports:
      - '8080:8080'
    volumes:
      - './exportet:/app'
    command: java -jar /app/rest-api-war.jar
    depends_on:
      - db
  webpage:
    image: tomcat
    ports:
      - '80:8080'
    volumes:
      - './exportet:/usr/local/tomcat/webapps'
    depends_on:
      - db
