version: '3'
services:
  db:
    image: 'mysql:8.0'
    environment:
      - max_sp_recursion_depth=255
      - MYSQL_ROOT_PASSWORD=DHO4A56W798347IUdg478n6i8342Aw567u8dza678WIN86
    volumes:
      - './docker/db:/var/lib/mysql'
      - './docker/mysql.cnf:/etc/my.cnf'
      - './docker/mysql.log:/custommysql.log'
    ports:
      - '100:3306'
  rest-api:
    image: 'openjdk:11'
    ports:
      - '8080:8080'
    volumes:
      - './bin/rest-api-war.jar:/app/bin.jar'
      - './local-admin.cfg:/app/config.cfg'
      - './logs:/app/logs'
    command: java -jar /app/bin.jar
    depends_on:
      - db
  webpage:
    image: 'tomcat:jdk11-openjdk'
    ports:
      - '80:8080'
    volumes:
      - './bin/ROOT.war:/usr/local/tomcat/webapps/ROOT.war'
      - './local-admin.cfg:/app/config.cfg'
      - './logs:/app/logs'
  service-worker:
    image: 'openjdk:11'
    volumes:
      - './bin/sw.jar:/app/bin.jar'
      - './docker/db-backup:/to'
      - './docker/db:/from'
      - './local-admin.cfg:/app/config.cfg'
      - './logs:/app/logs'
    command: java -jar /app/bin.jar
    depends_on:
      - db
  installer:
    image: 'debian:buster'
    volumes:
      - './:/project'
    environment:
      - version=1.2.1
    command: /project/scripts/docker-deb-installer.sh
