version: '3'
services:
  db:
    image: 'mysql:8.0'
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - max_sp_recursion_depth=12
    volumes:
      - './docker/db:/var/lib/mysql'
      - '/mysql.cnf:/etc/my.cnf'
      - './docker/mysql.log:/custommysql.log'
    ports:
      - '100:3306'
  rest-api:
    image: 'openjdk:11'
    ports:
      - '8080:8080'
    volumes:
      - './bin:/app'
      - './local-admin.cfg:/app/config.cfg'
      - './logs:/app/logs'
    command: java -jar /app/rest-api-war.jar
    depends_on:
      - db
  webpage:
    image: 'tomcat:jdk11-openjdk'
    ports:
      - '80:8080'
    volumes:
      - './bin:/usr/local/tomcat/webapps'
      - './local-admin.cfg:/app/config.cfg'
      - './logs:/app/logs'
    depends_on:
      - db
  service-worker:
    image: 'openjdk:11'
    volumes:
      - './bin:/app'
      - './docker/db-backup:/to'
      - './docker/db:/from'
      - './local-admin.cfg:/app/config.cfg'
      - './logs:/app/logs'
    command: java -jar /app/sw.jar
    depends_on:
      - db
  installer:
    image: 'debian:buster'
    volumes:
      - './:/project'
    environment:
      - version=1.2.1
    command: /project/scripts/docker-deb-installer.sh
